name: hello-pbr
options:
    bundleIdPrefix: google.filament
include: ../app-template.yml
configs:
    Metal Debug: debug
    Metal Release: release
    OpenGL Debug: debug
    OpenGL Release: release
targets:
    hello-pbr:
        sources: hello-pbr/
        templates:
            - FilamentApp
        settings:
            base:
                OTHER_LDFLAGS: ["-lfilameshio", "-lmeshoptimizer", "-limage"]
        preBuildScripts:
            - path: build-resources.sh
              name: Build Resources
