name: transparent-rendering
options:
    bundleIdPrefix: google.filament
include: ../app-template.yml
configs:
    Metal Debug: debug
    Metal Release: release
    OpenGL Debug: debug
    OpenGL Release: release
targets:
    transparent-rendering:
        sources: transparent-rendering/
        templates:
            - FilamentApp
        preBuildScripts:
            - path: build-materials.sh
              name: Build Materials
