name: hello-triangle
options:
    bundleIdPrefix: google.filament
include: ../app-template.yml
configs:
    Metal Debug: debug
    Metal Release: release
    OpenGL Debug: debug
    OpenGL Release: release
targets:
    hello-triangle:
        sources: hello-triangle/
        templates:
            - FilamentApp
        preBuildScripts:
            - path: build-materials.sh
              name: Build Materials
